name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@v1.10.2      
    - name: Build
      run: cargo installl --no-confirm bat
