name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@main
    - name: Build rust binary
      run: |
          cargo binstall --no-confirm bat
          # bat bottom du-dust fd-find git-delta hexyl lsd procs ripgrep \
          # starship tealdeer tree-sitter-cli vivid yazi-fm zoxide
    - name: Pack binary
      run: tar -czvf ~/rust_cli_tools.tar.gz -C ~/.cargo/bin .
    - uses: actions/upload-artifact@v4
      with:
        name: rust_cli_tools
        path: ~/rust_cli_tools.tar.gz
        retention-days: 1

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
    - name: Release
      run: gh release create v1.2.3 ./rust_cli_tools/*
      # uses: softprops/action-gh-release@v2
      # with:
      #   name: rust_cli_tools
      #   files: rust_cli_tools/rust_cli_tools.tar.gz
