name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@main
    - name: Build
      run: cargo binstall --no-confirm bat bottom du-dust fd-find git-delta hexyl lsd \
                 procs ripgrep starship tealdeer tree-sitter-cli vivid yazi-fm zoxide
